### ISSUE TITLE
[Enhancement]: remove the ability to set passwords in terraform

### ISSUE THREAD

**Issue by nicks** [docker/terraform-provider-docker#52]
### Description

currently the provider has a `password` argument. this is insecure and should be removed.

### Would you like to implement a fix?

None

**Comment by drdkmkkr** [comment]
Hi @nicks 

Any chance of re-adding the `password` provider input? Without it being insecure?

This would enable using enable using [provider configurations](https://docs.scalr.io/docs/provider_resource_scalr_provider_configuration#custom-providers) in Scalr.io, and maybe something similar in other tools as well.

Example:

```hcl
resource "scalr_provider_configuration" "dockerhub" {
  name = "docker-hub"
  
  custom {
    provider_name = "docker"
    argument {
      name = "username"
      value = "my-username"
    }
    
    argument {
      name = "password"
      value = "my-password"
    }
  }
}
```

Which effectively would result in
```hcl
provider "docker" {
  username = "my-username"
  password = "my-password"
}
```
