### ISSUE TITLE
[Enhancement]: Re-adding the `password` provider argument?

### ISSUE THREAD

**Issue by drdkmkkr** [docker/terraform-provider-docker#77]
### Description

Any chance of re-adding the `password` provider argument, which was removed in https://github.com/docker/terraform-provider-docker/issues/52? Without it being insecure? 

This would enable using the use of [provider configurations](https://docs.scalr.io/docs/provider_resource_scalr_provider_configuration#custom-providers) in Scalr.io and maybe something similar in other tools as well.

Example:

```hcl
resource "scalr_provider_configuration" "dockerhub" {
  name = "docker-hub"
  
  custom {
    provider_name = "docker"
    argument {
      name = "username"
      value = "my-username"
    }
    
    argument {
      name = "password"
      value = "my-password"
    }
  }
}
```

Which would result in:

```hcl
provider "docker" {
  username = "my-username"
  password = "my-password"
}
```

### Potential Terraform Configuration

```terraform

```

### Would you like to implement a fix?

None

**Comment by nicks** [comment]
Thanks for the request!

Ya I was really hoping to avoid this footgun but I can see how it would be useful for the scalr use-case

**Comment by drdkmkkr** [comment]
@nicks Thanks! Any chance this change can be published? 🙏
